import type { AiDirectorStoreState } from "@features/ai/model/aiDirectorStore";

export const selectAiDirectorViewState = (state: AiDirectorStoreState) => ({
  alertsHistory: state.alertsHistory,
  alertsHistoryDateFilter: state.alertsHistoryDateFilter,
  alertsHistoryShopFilter: state.alertsHistoryShopFilter,
  alertsHistoryShopOptions: state.alertsHistoryShopOptions,
  alertsHistoryTypeFilter: state.alertsHistoryTypeFilter,
  chatError: state.chatError,
  chatLoading: state.chatLoading,
  chatMessage: state.chatMessage,
  chatReply: state.chatReply,
  dayLabels: state.dayLabels,
  decisionsLog: state.decisionsLog,
  deepAnalysisDepth: state.deepAnalysisDepth,
  deepEmployees: state.deepEmployees,
  deepFocusAreas: state.deepFocusAreas,
  deepMeta: state.deepMeta,
  deepRiskSensitivity: state.deepRiskSensitivity,
  directorDecisions: state.directorDecisions,
  employees: state.employees,
  error: state.error,
  focusDropdownOpen: state.focusDropdownOpen,
  focusOptions: state.focusOptions,
  forecast: state.forecast,
  heatmap: state.heatmap,
  heatmapStops: state.heatmapStops,
  kpiNarrative: state.kpiNarrative,
  kpiNarrativeError: state.kpiNarrativeError,
  kpiNarrativeLoading: state.kpiNarrativeLoading,
  kpiNarrativeSections: state.kpiNarrativeSections,
  kpiNarrativeShopName: state.kpiNarrativeShopName,
  kpiSelectedShopUuid: state.kpiSelectedShopUuid,
  loading: state.loading,
  problemsSummary: state.problemsSummary,
  quickActionNote: state.quickActionNote,
  rating: state.rating,
  shiftHistoryDateFilter: state.shiftHistoryDateFilter,
  shiftHistoryShopFilter: state.shiftHistoryShopFilter,
  shiftHistoryShopOptions: state.shiftHistoryShopOptions,
  shiftSummariesHistory: state.shiftSummariesHistory,
  systemStatus: state.systemStatus,
  topKpi: state.topKpi,
});

export const selectAiDirectorActions = (state: AiDirectorStoreState) => ({
  applyDashboardData: state.applyDashboardData,
  setAlertsHistoryDateFilter: state.setAlertsHistoryDateFilter,
  setAlertsHistoryShopFilter: state.setAlertsHistoryShopFilter,
  setAlertsHistoryTypeFilter: state.setAlertsHistoryTypeFilter,
  setChatError: state.setChatError,
  setChatLoading: state.setChatLoading,
  setChatMessage: state.setChatMessage,
  setChatReply: state.setChatReply,
  setDeepAnalysisDepth: state.setDeepAnalysisDepth,
  setDeepRiskSensitivity: state.setDeepRiskSensitivity,
  setError: state.setError,
  setFocusDropdownOpen: state.setFocusDropdownOpen,
  setKpiNarrativeData: state.setKpiNarrativeData,
  setKpiNarrativeError: state.setKpiNarrativeError,
  setKpiNarrativeLoading: state.setKpiNarrativeLoading,
  setKpiSelectedShopUuid: state.setKpiSelectedShopUuid,
  setLoading: state.setLoading,
  setQuickActionNote: state.setQuickActionNote,
  setShiftHistoryDateFilter: state.setShiftHistoryDateFilter,
  setShiftHistoryShopFilter: state.setShiftHistoryShopFilter,
  toggleFocus: state.toggleFocus,
});
